using System.Buffers.Binary;

namespace OpenMaui.AppImage.Core;

/// <summary>
/// Result of staging the FHS install tree shared by the .deb and .rpm writers.
/// </summary>
/// <param name="Root">Staging directory; its contents map to "/" on the target.</param>
/// <param name="Files">Absolute target paths of the files outside the /opt app directory (launcher, desktop file, icons, metainfo).</param>
public sealed record StagedTree(string Root, IReadOnlyList<string> Files);

/// <summary>
/// Builds the install tree for system packages:
/// <code>
/// /opt/&lt;app-id&gt;/                          publish output (self-contained)
/// /usr/bin/&lt;package-name&gt;                 launcher wrapper script
/// /usr/share/applications/&lt;app-id&gt;.desktop
/// /usr/share/icons/hicolor/&lt;size&gt;/apps/&lt;app-id&gt;.{svg,png}
/// /usr/share/metainfo/&lt;app-id&gt;.metainfo.xml   (with --metainfo)
/// </code>
/// Every file and directory gets an explicit mode (0755 dirs/executables,
/// 0644 everything else) so the result does not depend on the umask or on
/// the modes dotnet publish happened to write.
/// </summary>
public static class NativeLayoutBuilder
{
    public const UnixFileMode DirMode =
        UnixFileMode.UserRead | UnixFileMode.UserWrite | UnixFileMode.UserExecute |
        UnixFileMode.GroupRead | UnixFileMode.GroupExecute |
        UnixFileMode.OtherRead | UnixFileMode.OtherExecute;

    public const UnixFileMode ExecMode = DirMode;

    public const UnixFileMode FileMode =
        UnixFileMode.UserRead | UnixFileMode.UserWrite |
        UnixFileMode.GroupRead |
        UnixFileMode.OtherRead;

    /// <summary>Icon sizes the hicolor theme defines as fixed-size directories.</summary>
    public static readonly int[] HicolorSizes = { 16, 22, 24, 32, 36, 48, 64, 72, 96, 128, 192, 256, 512 };

    public static StagedTree Stage(string stagingRoot, string publishDir, NativePackageMetadata meta,
        FileInfo? icon, bool generateMetainfo, string? developer)
    {
        Directory.CreateDirectory(stagingRoot);
        var files = new List<string>();

        // /opt/<app-id>: the publish output
        var optDir = Combine(stagingRoot, meta.InstallDir);
        CopyTree(publishDir, optDir);

        // /usr/bin/<package-name>
        var launcher = Combine(stagingRoot, meta.LauncherPath);
        Directory.CreateDirectory(Path.GetDirectoryName(launcher)!);
        File.WriteAllText(launcher, GenerateLauncherScript(meta));
        files.Add(meta.LauncherPath);

        // /usr/share/applications/<app-id>.desktop
        var desktopTarget = $"/usr/share/applications/{meta.DesktopFileName}";
        var desktop = Combine(stagingRoot, desktopTarget);
        Directory.CreateDirectory(Path.GetDirectoryName(desktop)!);
        File.WriteAllText(desktop, GenerateDesktopEntry(meta));
        files.Add(desktopTarget);

        // Icons
        files.AddRange(StageIcons(stagingRoot, optDir, meta, icon));

        // AppStream metainfo
        if (generateMetainfo)
        {
            var metainfoTarget = $"/usr/share/metainfo/{meta.AppId}.metainfo.xml";
            var metainfo = Combine(stagingRoot, metainfoTarget);
            Directory.CreateDirectory(Path.GetDirectoryName(metainfo)!);
            File.WriteAllText(metainfo, AppStreamGenerator.Generate(
                meta.AppId, meta.AppName, meta.Summary,
                desktopFileId: meta.DesktopFileName,
                binaryName: meta.PackageName,
                developerName: developer));
            files.Add(metainfoTarget);
        }

        ApplyModes(stagingRoot, Combine(stagingRoot, $"{meta.InstallDir}/{meta.ExecutableName}"),
            Combine(stagingRoot, meta.LauncherPath));

        return new StagedTree(stagingRoot, files);
    }

    /// <summary>Launcher wrapper installed as /usr/bin/&lt;package-name&gt;.</summary>
    public static string GenerateLauncherScript(NativePackageMetadata meta)
    {
        var target = meta.Runtime == DotNetRuntimeKind.FrameworkDependent
            ? $"exec dotnet \"{meta.InstallDir}/{meta.ExecutableName}.dll\" \"$@\""
            : $"exec \"{meta.InstallDir}/{meta.ExecutableName}\" \"$@\"";
        return $"#!/bin/sh\n# {meta.AppName} launcher (generated by openmaui-appimage)\n{target}\n";
    }

    /// <summary>Desktop entry for /usr/share/applications/&lt;app-id&gt;.desktop.</summary>
    public static string GenerateDesktopEntry(NativePackageMetadata meta)
    {
        // WM_CLASS is the app name without spaces or underscores (matches X11Window.cs)
        var wmClass = meta.AppName.Replace(" ", "").Replace("_", "");
        var category = meta.Category.TrimEnd(';');
        return $"""
            [Desktop Entry]
            Type=Application
            Name={meta.AppName}
            Comment={meta.Summary}
            Exec={meta.PackageName}
            Icon={meta.AppId}
            Categories={category};
            Terminal=false
            StartupWMClass={wmClass}

            """;
    }

    /// <summary>Placeholder icon used when the app has none (same design as the AppImage path).</summary>
    public static string PlaceholderSvg(string appName) => $@"<?xml version=""1.0"" encoding=""UTF-8""?>
<svg width=""256"" height=""256"" viewBox=""0 0 256 256"" xmlns=""http://www.w3.org/2000/svg"">
  <rect width=""256"" height=""256"" rx=""32"" fill=""#2196F3""/>
  <text x=""128"" y=""160"" font-family=""sans-serif"" font-size=""120"" font-weight=""bold""
        text-anchor=""middle"" fill=""white"">{AppStreamGenerator.Escape(appName[..1])}</text>
</svg>";

    /// <summary>
    /// Target hicolor path for an icon: SVG goes to scalable/apps; a PNG goes to
    /// its own square size when that is a standard hicolor size, otherwise 256x256.
    /// Returns null for formats the icon theme cannot use (e.g. .ico).
    /// </summary>
    public static string? HicolorTarget(string iconPath, string appId)
    {
        var ext = Path.GetExtension(iconPath).ToLowerInvariant();
        if (ext == ".svg")
            return $"/usr/share/icons/hicolor/scalable/apps/{appId}.svg";
        if (ext != ".png")
            return null;

        var size = ReadPngSize(iconPath);
        var dir = size is { } s && s.Width == s.Height && HicolorSizes.Contains(s.Width)
            ? $"{s.Width}x{s.Width}"
            : "256x256";
        return $"/usr/share/icons/hicolor/{dir}/apps/{appId}.png";
    }

    /// <summary>Reads width/height from a PNG IHDR chunk, or null when not a PNG.</summary>
    public static (int Width, int Height)? ReadPngSize(string path)
    {
        try
        {
            using var fs = File.OpenRead(path);
            var header = new byte[24];
            if (fs.Read(header, 0, 24) < 24)
                return null;
            byte[] sig = { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
            if (!header.AsSpan(0, 8).SequenceEqual(sig))
                return null;
            var w = BinaryPrimitives.ReadInt32BigEndian(header.AsSpan(16, 4));
            var h = BinaryPrimitives.ReadInt32BigEndian(header.AsSpan(20, 4));
            return (w, h);
        }
        catch
        {
            return null;
        }
    }

    private static IEnumerable<string> StageIcons(string stagingRoot, string optDir,
        NativePackageMetadata meta, FileInfo? icon)
    {
        var staged = new List<string>();
        string? themeTarget = null;
        string? themeSource = null;

        if (icon is { Exists: true })
        {
            themeTarget = HicolorTarget(icon.FullName, meta.AppId);
            themeSource = icon.FullName;
            if (themeTarget == null)
                Console.WriteLine($"  Warning: icon '{icon.Name}' is not SVG or PNG; the icon theme gets a placeholder. Pass --icon with an SVG or PNG.");

            // Runtime window icon: the app looks for appicon.<ext> next to its binary
            var ext = icon.Extension.ToLowerInvariant();
            var runtimeIcon = Path.Combine(optDir, $"appicon{ext}");
            if (!File.Exists(runtimeIcon))
                File.Copy(icon.FullName, runtimeIcon);
        }

        if (themeTarget == null)
        {
            themeTarget = $"/usr/share/icons/hicolor/scalable/apps/{meta.AppId}.svg";
            var dest = Combine(stagingRoot, themeTarget);
            Directory.CreateDirectory(Path.GetDirectoryName(dest)!);
            File.WriteAllText(dest, PlaceholderSvg(meta.AppName));

            var runtimeIcon = Path.Combine(optDir, "appicon.svg");
            if (!File.Exists(runtimeIcon) && icon is not { Exists: true })
                File.WriteAllText(runtimeIcon, PlaceholderSvg(meta.AppName));
        }
        else
        {
            var dest = Combine(stagingRoot, themeTarget);
            Directory.CreateDirectory(Path.GetDirectoryName(dest)!);
            File.Copy(themeSource!, dest, overwrite: true);
        }

        staged.Add(themeTarget);
        return staged;
    }

    /// <summary>
    /// Mode for a payload file: ELF executables and shell scripts that were
    /// executable get 0755; shared libraries and everything else 0644.
    /// </summary>
    public static UnixFileMode DecideFileMode(string path)
    {
        var name = Path.GetFileName(path);
        var isSharedLib = name.EndsWith(".so", StringComparison.Ordinal) || name.Contains(".so.", StringComparison.Ordinal);

        byte[] head = new byte[4];
        int read;
        try
        {
            using var fs = File.OpenRead(path);
            read = fs.Read(head, 0, 4);
        }
        catch
        {
            return FileMode;
        }

        if (read >= 4 && head[0] == 0x7F && head[1] == 'E' && head[2] == 'L' && head[3] == 'F')
            return isSharedLib ? FileMode : ExecMode;

        if (read >= 2 && head[0] == '#' && head[1] == '!')
        {
            var current = File.GetUnixFileMode(path);
            if ((current & UnixFileMode.UserExecute) != 0)
                return ExecMode;
        }

        return FileMode;
    }

    private static void ApplyModes(string root, string mainExecutable, string launcher)
    {
        foreach (var dir in Directory.EnumerateDirectories(root, "*", SearchOption.AllDirectories).Prepend(root))
            File.SetUnixFileMode(dir, DirMode);

        foreach (var file in Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories))
        {
            var mode = file == mainExecutable || file == launcher ? ExecMode : DecideFileMode(file);
            File.SetUnixFileMode(file, mode);
        }
    }

    private static void CopyTree(string source, string destination)
    {
        Directory.CreateDirectory(destination);
        foreach (var file in Directory.GetFiles(source))
        {
            // Follow symlinks: the payload carries regular files only
            File.Copy(file, Path.Combine(destination, Path.GetFileName(file)), overwrite: true);
        }
        foreach (var dir in Directory.GetDirectories(source))
            CopyTree(dir, Path.Combine(destination, Path.GetFileName(dir)));
    }

    /// <summary>Joins the staging root with an absolute target path.</summary>
    public static string Combine(string root, string targetPath) =>
        Path.Combine(root, targetPath.TrimStart('/'));
}
