using System.Text;

namespace OpenMaui.AppImage.Core;

/// <summary>
/// Builds a binary RPM from the staged tree by generating a spec whose
/// %install step copies the prebuilt files, then running
/// <c>rpmbuild -bb</c> with its own <c>_topdir</c> in a temp directory
/// (no root, nothing written to ~/rpmbuild).
///
/// The spec turns off everything that would alter the .NET payload or
/// second-guess the declared dependencies: no debuginfo split, no brp
/// strip/mangle scripts, no build-id links, and AutoReqProv off (otherwise
/// rpm would export every bundled .so as a system-wide Provides).
/// </summary>
public static class RpmPackageBuilder
{
    public const string MissingRpmbuildMessage =
        "rpmbuild not found. Building .rpm packages needs it:\n" +
        "  Fedora/RHEL:   sudo dnf install rpm-build\n" +
        "  Debian/Ubuntu: sudo apt install rpm\n" +
        "  openSUSE:      sudo zypper install rpm-build";

    /// <summary>Generates the spec file. <paramref name="stagingRoot"/> is copied into %{buildroot}.</summary>
    public static string GenerateSpec(NativePackageMetadata meta, NativeDependencies deps,
        StagedTree staged, string? vendor = null)
    {
        var sb = new StringBuilder();
        sb.Append("# Generated by openmaui-appimage\n");
        sb.Append("%global debug_package %{nil}\n");
        sb.Append("%global _enable_debug_packages 0\n");
        sb.Append("%global __os_install_post %{nil}\n");
        sb.Append("%global __arch_install_post %{nil}\n");
        sb.Append("%global _build_id_links none\n");
        sb.Append('\n');
        sb.Append("Name:           ").Append(meta.PackageName).Append('\n');
        sb.Append("Version:        ").Append(meta.RpmVersion).Append('\n');
        sb.Append("Release:        ").Append(Escape(meta.Release)).Append('\n');
        sb.Append("Summary:        ").Append(Escape(OneLine(meta.Summary))).Append('\n');
        sb.Append("License:        ").Append(Escape(OneLine(meta.License))).Append('\n');
        if (!string.IsNullOrWhiteSpace(meta.Homepage))
            sb.Append("URL:            ").Append(Escape(OneLine(meta.Homepage))).Append('\n');
        sb.Append("Packager:       ").Append(Escape(OneLine(meta.Maintainer))).Append('\n');
        if (!string.IsNullOrWhiteSpace(vendor))
            sb.Append("Vendor:         ").Append(Escape(OneLine(vendor))).Append('\n');
        if (meta.Architecture.IsIndependent)
            sb.Append("BuildArch:      noarch\n");
        sb.Append("AutoReqProv:    no\n");
        foreach (var req in deps.RpmRequires)
            sb.Append("Requires:       ").Append(req).Append('\n');
        foreach (var rec in deps.RpmRecommends)
            sb.Append("Recommends:     ").Append(rec).Append('\n');
        sb.Append('\n');

        sb.Append("%description\n");
        var description = string.IsNullOrWhiteSpace(meta.Description) ? meta.Summary : meta.Description.Trim();
        sb.Append(Escape(description.Replace("\r\n", "\n"))).Append('\n');
        foreach (var note in deps.Notes.Where(n => n.Contains("dnf", StringComparison.Ordinal)))
            sb.Append('\n').Append(Escape(note)).Append('\n');
        sb.Append('\n');

        sb.Append("%install\n");
        sb.Append("mkdir -p %{buildroot}\n");
        sb.Append("cp -a ").Append(ShellQuote(Escape(staged.Root) + "/.")).Append(" %{buildroot}/\n");
        sb.Append('\n');

        sb.Append("%files\n");
        sb.Append("%defattr(-,root,root,-)\n");
        sb.Append(QuotePath(meta.InstallDir)).Append('\n');
        foreach (var file in staged.Files)
            sb.Append(QuotePath(file)).Append('\n');
        sb.Append('\n');

        // One entry so rpm can derive SOURCE_DATE_EPOCH from it (Fedora's default)
        var date = DebPackageWriter.ResolveMtime().UtcDateTime
            .ToString("ddd MMM dd yyyy", System.Globalization.CultureInfo.InvariantCulture);
        sb.Append("%changelog\n");
        sb.Append("* ").Append(date).Append(' ').Append(Escape(OneLine(meta.Maintainer)))
            .Append(" - ").Append(meta.RpmVersion).Append('-').Append(Escape(meta.Release)).Append('\n');
        sb.Append("- Package built by openmaui-appimage\n");

        return sb.ToString();
    }

    /// <summary>rpmbuild argument vector for building <paramref name="specPath"/> under <paramref name="topDir"/>.</summary>
    public static List<string> BuildArguments(string specPath, string topDir, PackageArchitecture arch)
    {
        var args = new List<string>
        {
            "-bb",
            "--quiet",
            "--define", $"_topdir {topDir}",
            "--define", "_build_id_links none"
        };
        if (!arch.IsIndependent)
        {
            args.Add("--target");
            args.Add(arch.Rpm);
        }
        args.Add(specPath);
        return args;
    }

    /// <summary>Runs rpmbuild and moves the resulting .rpm to <paramref name="outputPath"/>.</summary>
    public static async Task<bool> BuildAsync(StagedTree staged, NativePackageMetadata meta,
        NativeDependencies deps, string outputPath, string workDir, string? vendor = null)
    {
        var rpmbuild = ProcessRunner.FindOnPath("rpmbuild");
        if (rpmbuild == null)
        {
            Console.Error.WriteLine("Error: " + MissingRpmbuildMessage);
            return false;
        }

        var topDir = Path.Combine(workDir, "rpmbuild");
        Directory.CreateDirectory(Path.Combine(topDir, "SPECS"));
        var specPath = Path.Combine(topDir, "SPECS", $"{meta.PackageName}.spec");
        await File.WriteAllTextAsync(specPath, GenerateSpec(meta, deps, staged, vendor));

        var exit = await ProcessRunner.RunCommandAsync(rpmbuild, BuildArguments(specPath, topDir, meta.Architecture));
        if (exit != 0)
        {
            Console.Error.WriteLine($"Error: rpmbuild failed (exit {exit}). Spec: {specPath}");
            return false;
        }

        var built = Directory.Exists(Path.Combine(topDir, "RPMS"))
            ? Directory.GetFiles(Path.Combine(topDir, "RPMS"), "*.rpm", SearchOption.AllDirectories).FirstOrDefault()
            : null;
        if (built == null)
        {
            Console.Error.WriteLine($"Error: rpmbuild reported success but produced no .rpm under {topDir}/RPMS.");
            return false;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(outputPath))!);
        File.Move(built, outputPath, overwrite: true);
        return true;
    }

    /// <summary>Escapes rpm macro characters in free text.</summary>
    public static string Escape(string value) => value.Replace("%", "%%");

    private static string QuotePath(string path) => $"\"{Escape(path)}\"";

    private static string ShellQuote(string value) => "'" + value.Replace("'", "'\\''") + "'";

    private static string OneLine(string value) =>
        value.Replace("\r", " ").Replace("\n", " ").Trim();
}
